name: Update GitHub Profile Stats

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Git
        run: |
          git config --global user.name "ravin00"
          git config --global user.email "ravinbandara76@gmail.com"

      - name: Update README
        run: |
          git diff --quiet || (git add README.md && git commit -m "Update README stats")

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/ravin00/ravin00.git" HEAD:main
