name: Update GitHub Activity

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest GitHub activity
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Git
        run: |
          git config --global user.name "ravin00"
          git config --global user.email "it22354174@my.sliit.lk"

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your update script goes here, for example:
          # echo "Updating README with GitHub activity"

          # Check if README.md is modified
          git diff --quiet || (git add README.md && git commit -m "Update README stats" && git push)
